"""Generated supported-formats reference page — FMT-1.2 (#5413).

``docs/guide/import-a-spec.md`` used to state *"Supported inputs: OpenAPI 3.x, Swagger 2.0,
Arazzo 1.0, JSON Schema 2020-12"*. That is true of the **Projects** importer and silent about the
Catalog importer carrying the other thirty-nine formats, so an evaluator reading our documentation
concluded Apiome supports four. A second copy of the list lived in the UI's format gallery. Three
sources of truth, no way to keep them aligned.

This module removes the prose claim by **deriving** the page from the registries that already know
the answer:

* :func:`app.import_source.describe_import_sources` — every registered import adapter, its label,
  paradigm, input kinds, live-discovery capability, emitted format keys, declared file extensions
  (FMT-1.1) and runtime availability.
* :func:`app.emitter.describe_emit_targets` — every registered emitter, so the page can state
  whether a format is import-only, export-only, or round-trips.
* :func:`app.format_capability_registry.capability_for` — the reviewed capability entry behind each
  format, so the page carries the registry's own boundary statement rather than a fresh assertion.
* :data:`app.import_routing.PUBLISHABLE_FORMATS` — the server-side rule that decides whether an
  import becomes a publishable Project or a catalog item, so the Projects/Catalog split on the page
  is the routing code's rule and not a restatement of it.

The rendering is kept here (rather than in the script that writes the file) so a test can regenerate
the page in memory and compare it byte-for-byte against the committed copy. That test is the drift
gate: the pytest suite runs in CI, so a registry change that is not accompanied by a regenerated
page turns the build red.

Everything here is **pure and deterministic** — same registries in, same bytes out — because a
generator whose output wobbles between runs cannot be drift-checked at all.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Tuple

from .canonical_model import ApiParadigm
from .emitter import available_emit_formats, get_emitter
from .format_capability_registry import (
    CapabilityProvenance,
    NativeHierarchy,
    capability_for,
)
from .import_routing import PUBLISHABLE_FORMATS
from .import_source import (
    ImportSourceDescriptor,
    describe_import_sources,
    get_import_source,
    resolve_import_source_key,
)

__all__ = [
    "SUPPORTED_FORMATS_DOCS_PAGE",
    "REGENERATE_COMMAND",
    "FormatRow",
    "collect_format_rows",
    "render_supported_formats_page",
]

#: Path of the generated page, relative to the monorepo root.
SUPPORTED_FORMATS_DOCS_PAGE = "docs/guide/supported-formats.md"

#: The one command that regenerates the page. Quoted in the file header and in the drift test's
#: failure message, so a contributor who breaks the gate is told exactly how to fix it.
REGENERATE_COMMAND = "cd apiome-rest && uv run python scripts/generate_supported_formats_doc.py"

#: Paradigm section order and heading. Fixed rather than sorted so the page reads from the most
#: familiar paradigm to the most specialized, and so adding a paradigm is a deliberate edit here.
_PARADIGM_SECTIONS: Tuple[Tuple[ApiParadigm, str], ...] = (
    (ApiParadigm.REST, "REST"),
    (ApiParadigm.RPC, "RPC"),
    (ApiParadigm.EVENT, "Event"),
    (ApiParadigm.GRAPH, "Graph"),
    (ApiParadigm.DATA_SCHEMA, "Data schema"),
    (ApiParadigm.AGENT, "Agent"),
)

#: Registry keys that are internal machinery rather than a format a reader can use. ``sample`` is
#: the no-op acceptance adapter that exercises the job pipeline; documenting it as a supported
#: format would be exactly the kind of over-claim this page exists to end.
_INTERNAL_KEYS: frozenset[str] = frozenset({"sample"})

#: The em dash used for "not applicable" cells, so an empty cell never reads as a missing fact.
_NONE = "—"

#: Module prefix of an adapter/emitter this repository ships.
#:
#: The page documents **what Apiome ships**, so it is built from adapters defined under ``app.``
#: rather than from whatever happens to be in the process-wide registry. Two things depend on this:
#: the generated bytes stay a function of the source tree (a registry a caller has added to at
#: runtime cannot silently rewrite a committed doc), and the drift gate stays meaningful under
#: pytest, where sibling test modules register throwaway adapters and do not always remove them.
_SHIPPED_MODULE_PREFIX = "app."


def _is_shipped_import_source(key: str) -> bool:
    """Whether ``key`` names an adapter defined in this repository."""
    adapter = get_import_source(key)
    return adapter is not None and type(adapter).__module__.startswith(_SHIPPED_MODULE_PREFIX)


def _shipped_emitters() -> Dict[str, Tuple[str, bool]]:
    """Map each shipped emitter onto the import-source key it corresponds to.

    Iterates the emitter **registry keys** rather than descriptor keys: the two are not always the
    same string (the AsyncAPI emitter registers under ``asyncapi-3`` but describes itself as
    ``asyncapi``), so a lookup by descriptor key silently misses those emitters and the page would
    report a round-tripping format as import-only.

    The descriptor key is then resolved through :func:`~app.import_source.resolve_import_source_key`,
    which already owns the alias table that reconciles the two registries (``protobuf`` → ``grpc``),
    rather than a second mapping being invented here that could drift from it.

    Returns:
        ``{import_source_key: (emitter_label, available)}``, first by sorted registry key so the
        result is deterministic.
    """
    mapping: Dict[str, Tuple[str, bool]] = {}
    for format_key in available_emit_formats():
        emitter = get_emitter(format_key)
        if emitter is None or not emitter.__module__.startswith(_SHIPPED_MODULE_PREFIX):
            continue
        descriptor = emitter.descriptor()
        if descriptor.key in _INTERNAL_KEYS:
            continue
        mapping.setdefault(
            resolve_import_source_key(descriptor.key),
            (descriptor.label, descriptor.available),
        )
    return mapping


def _escape_cell(text: str) -> str:
    """Make ``text`` safe inside a Markdown table cell.

    A literal ``|`` would end the cell and silently shift every column after it, and a newline
    would end the row. Both are escaped/flattened rather than dropped, so no registry prose is lost.

    Args:
        text: Raw text from a registry descriptor or capability entry.

    Returns:
        The text with pipes escaped and all whitespace collapsed to single spaces.
    """
    return " ".join(text.replace("|", "\\|").split())


def _code_list(values: Sequence[str]) -> str:
    """Render ``values`` as comma-separated inline code, or the not-applicable dash.

    Args:
        values: Already-ordered tokens (format keys, extensions, input kinds).

    Returns:
        ``` `a`, `b` ``` style Markdown, or :data:`_NONE` when the sequence is empty.
    """
    if not values:
        return _NONE
    return ", ".join(f"`{_escape_cell(v)}`" for v in values)


@dataclass(frozen=True)
class FormatRow:
    """One format's row on the generated page.

    Every field is read from a registry — nothing here is asserted by this module — so a row is a
    view of the running system rather than a claim about it.
    """

    key: str
    label: str
    paradigm: ApiParadigm
    input_kinds: Tuple[str, ...]
    supports_live_discovery: bool
    format_keys: Tuple[str, ...]
    file_extensions: Tuple[str, ...]
    can_import: bool
    can_export: bool
    export_label: Optional[str]
    publishable: bool
    import_available: bool
    import_unavailable_reason: Optional[str]
    export_available: bool
    native_hierarchy: NativeHierarchy
    provenance: CapabilityProvenance
    boundary_notes: Tuple[str, ...]

    @property
    def direction(self) -> str:
        """The import/export column value: what a reader can actually do with this format."""
        if self.can_import and self.can_export:
            return "Import + export"
        if self.can_import:
            return "Import only"
        if self.can_export:
            return "Export only"
        return _NONE  # pragma: no cover - a row exists because one of the two is true

    @property
    def anchor(self) -> str:
        """The stable HTML anchor for this format's boundary entry."""
        return f"format-{self.key}"


def _emitters_by_import_key() -> Dict[str, str]:
    """``{import_source_key: emitter_label}`` for every shipped emitter."""
    return {key: label for key, (label, _available) in _shipped_emitters().items()}


def _emitter_availability() -> Dict[str, bool]:
    """``{import_source_key: can_run_here}`` for every shipped emitter."""
    return {key: available for key, (_label, available) in _shipped_emitters().items()}


def _is_publishable(descriptor: ImportSourceDescriptor) -> bool:
    """Whether importing this format mints a publishable Project rather than a catalog item.

    Reads :data:`app.import_routing.PUBLISHABLE_FORMATS` — the exact set
    :func:`~app.import_routing.decide_import_routing` branches on — so the page cannot claim a
    routing the server would not perform.

    Args:
        descriptor: The adapter's registry descriptor.

    Returns:
        ``True`` when any format key the adapter emits is a publishable one.
    """
    return any(fmt.strip().lower() in PUBLISHABLE_FORMATS for fmt in descriptor.formats)


def collect_format_rows() -> List[FormatRow]:
    """Build one :class:`FormatRow` per documented format, sorted by label then key.

    Every registered import adapter contributes a row, plus any emitter with no import adapter
    behind it (an export-only destination), so a format cannot be supported and undocumented.
    Internal machinery (:data:`_INTERNAL_KEYS`) is excluded.

    Returns:
        The rows, deterministically ordered.
    """
    emitters = _emitters_by_import_key()
    emitter_available = _emitter_availability()
    rows: List[FormatRow] = []
    covered: set[str] = set()

    for descriptor in describe_import_sources():
        if descriptor.key in _INTERNAL_KEYS or not _is_shipped_import_source(descriptor.key):
            continue
        covered.add(descriptor.key)
        capability = capability_for(descriptor.key)
        rows.append(
            FormatRow(
                key=descriptor.key,
                label=descriptor.label,
                paradigm=descriptor.paradigm,
                input_kinds=tuple(kind.value for kind in descriptor.input_kinds),
                supports_live_discovery=descriptor.supports_live_discovery,
                format_keys=tuple(descriptor.formats),
                file_extensions=tuple(descriptor.file_extensions),
                can_import=True,
                can_export=descriptor.key in emitters,
                export_label=emitters.get(descriptor.key),
                publishable=_is_publishable(descriptor),
                import_available=descriptor.available,
                import_unavailable_reason=descriptor.unavailable_reason,
                export_available=emitter_available.get(descriptor.key, True),
                native_hierarchy=capability.native_hierarchy,
                provenance=capability.provenance,
                boundary_notes=tuple(capability.notes),
            )
        )

    # An emitter with no import adapter is an export-only destination. It still belongs on a page
    # whose whole point is that the format surface is stated in full.
    for import_key, label in sorted(emitters.items()):
        if import_key in covered:
            continue
        capability = capability_for(import_key)
        rows.append(
            FormatRow(
                key=import_key,
                label=label,
                paradigm=ApiParadigm(capability.paradigm) if capability.paradigm else ApiParadigm.REST,
                input_kinds=(),
                supports_live_discovery=False,
                format_keys=(),
                file_extensions=(),
                can_import=False,
                can_export=True,
                export_label=label,
                publishable=False,
                import_available=False,
                import_unavailable_reason=None,
                export_available=emitter_available.get(import_key, True),
                native_hierarchy=capability.native_hierarchy,
                provenance=capability.provenance,
                boundary_notes=tuple(capability.notes),
            )
        )

    rows.sort(key=lambda row: (row.label.lower(), row.key))
    return rows


def _availability_cell(row: FormatRow) -> str:
    """Render the runtime-availability cell for one row.

    A format whose adapter hard-requires an absent toolchain is reported as unavailable **with the
    reason**, because "gRPC is unsupported" and "this deployment has no `buf`" are different facts
    and only one of them is about the product.
    """
    if row.can_import and not row.import_available:
        reason = row.import_unavailable_reason or "Requires a toolchain absent from this runtime."
        return f"Needs toolchain — {_escape_cell(reason)}"
    if row.can_export and not row.export_available:
        return "Export needs a toolchain absent from this runtime"
    return "Ready"


def _hierarchy_cell(row: FormatRow) -> str:
    """Render the analysis-fidelity cell, linking to the format's boundary entry.

    ``native`` means the analyzer keeps the format's own vocabulary (an X12 envelope stays an
    envelope); ``generic`` means the format-blind walk. A reviewed entry links to its notes.
    """
    if row.native_hierarchy is NativeHierarchy.NATIVE:
        text = "Format-native"
    elif row.native_hierarchy is NativeHierarchy.GENERIC:
        text = "Generic"
    else:
        text = _NONE
    if row.provenance is CapabilityProvenance.REVIEWED:
        return f"[{text} (reviewed)](#{row.anchor})"
    return text


def _format_table(rows: Sequence[FormatRow]) -> List[str]:
    """Render the Markdown table for one paradigm section.

    Args:
        rows: The rows in that paradigm, already ordered.

    Returns:
        The table's lines, header first.
    """
    lines = [
        "| Format | Key | Direction | Publishable | Input kinds | Live discovery "
        "| Format keys | File extensions | Analysis | Runtime |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                (
                    _escape_cell(row.label),
                    f"`{_escape_cell(row.key)}`",
                    row.direction,
                    "Project" if row.publishable else "Catalog",
                    _code_list(row.input_kinds),
                    "Yes" if row.supports_live_discovery else _NONE,
                    _code_list(row.format_keys),
                    _code_list(row.file_extensions),
                    _hierarchy_cell(row),
                    _availability_cell(row),
                )
            )
            + " |"
        )
    return lines


def _header(rows: Sequence[FormatRow]) -> List[str]:
    """Render the page header: the generated-file warning and the headline counts."""
    importable = [r for r in rows if r.can_import]
    exportable = [r for r in rows if r.can_export]
    both = [r for r in rows if r.can_import and r.can_export]
    catalog = [r for r in importable if not r.publishable]
    discovery = [r for r in importable if r.supports_live_discovery]

    return [
        "# Supported formats",
        "",
        "<!-- GENERATED FILE — do not edit by hand.",
        f"     Regenerate with: {REGENERATE_COMMAND} -->",
        "",
        "Every format Apiome reads or writes, generated from the running registries — the "
        "import-source registry, the emitter registry, and the source-format capability registry. "
        "It is regenerated by one command and drift-checked in CI, so this page cannot quietly "
        "fall behind the code the way a hand-maintained list does.",
        "",
        f"- **{len(importable)} formats can be imported.**",
        f"- **{len(exportable)} formats can be exported.**",
        f"- **{len(both)} round-trip** — import *and* export.",
        f"- **{len(discovery)}** can introspect a live endpoint rather than reading a file.",
        "",
        "## Which importer handles which format",
        "",
        "Apiome has two importers, and which one a format uses is decided by the server "
        "(`app.import_routing`), not by where you started:",
        "",
        "- **OpenAPI and Swagger become a publishable Project.** They normalize onto the editable "
        "class/path model, so they can be versioned, linted and published. This is the "
        "**Projects importer**, and its four format keys (`openapi-3.0`, `openapi-3.1`, "
        "`openapi-3.2`, `swagger-2.0`) are the set the older documentation described as the whole "
        "of Apiome's format support.",
        f"- **The other {len(catalog)} formats become a catalog item.** Protobuf, GraphQL, "
        "AsyncAPI, Thrift, EDI X12, COBOL copybooks, FHIR, HL7 v2 and the rest are imported by "
        "the **Catalog importer** and stored with their own structure intact rather than being "
        "forced into the OpenAPI shape. Catalog items are searchable, diffable and convertible; "
        "they are not publishable until converted.",
        "",
        "The **Direction** column below says whether a format can be imported, exported, or both. "
        "The **Publishable** column says which of the two importers claims it.",
        "",
        "## Reading the table",
        "",
        "| Column | Meaning |",
        "| --- | --- |",
        "| **Key** | The stable registry key. This is the `source_kind` the REST API "
        "and CLI take. |",
        "| **Direction** | Whether the format can be imported, exported, or both. |",
        "| **Publishable** | `Project` mints a publishable project; `Catalog` stores a "
        "catalog item. Routing branches on the format a document *normalizes to*, not the "
        "tool that read it — so a format that converts to OpenAPI first (TypeSpec, say) "
        "produces a Project on that path. |",
        "| **Input kinds** | How a document can reach the adapter: uploaded `file`, `url`, "
        "pasted `paste`, live `discovery`, or a multi-file `fileset` (an archive or "
        "repository). |",
        "| **Live discovery** | The adapter can introspect a running endpoint instead of "
        "reading a document. |",
        "| **Format keys** | The version coverage — every format string the adapter emits, "
        "so a specific version can be requested. |",
        "| **File extensions** | What the file pickers offer for this format. Advisory: "
        "content sniffing decides, so an unlisted extension is still accepted. |",
        "| **Analysis** | `Format-native` keeps the format's own vocabulary (an X12 envelope "
        "stays an envelope); `Generic` uses the format-blind walk. Reviewed entries link to "
        "their boundary notes. |",
        "| **Runtime** | `Ready`, or the toolchain this deployment is missing. An unavailable "
        "format is still *supported* — this deployment just cannot run it. |",
        "",
    ]


def _boundaries_section(rows: Sequence[FormatRow]) -> List[str]:
    """Render the reviewed-boundary notes.

    Only formats whose capability entry is **reviewed** contribute prose. A derived entry states
    only what the adapter declared about itself, which is not a boundary statement anyone reviewed,
    and printing it here would dress an inference up as a promise.
    """
    reviewed = [r for r in rows if r.provenance is CapabilityProvenance.REVIEWED and r.boundary_notes]
    lines = [
        "## Format boundaries",
        "",
        "What these formats knowingly do **not** model, from the source-format capability registry "
        "(`GET /v1/import/format-capabilities`). Only reviewed entries appear: every other format's "
        "entry is derived from its adapter's own declarations, which is not a reviewed claim about "
        "boundaries and is not presented as one here.",
        "",
    ]
    if not reviewed:  # pragma: no cover - the registry ships reviewed entries
        lines.extend(["*No reviewed boundary entries are registered.*", ""])
        return lines

    for row in reviewed:
        lines.append(f'<a id="{row.anchor}"></a>')
        lines.append("")
        lines.append(f"### {row.label}")
        lines.append("")
        for note in row.boundary_notes:
            lines.append(f"- {' '.join(note.split())}")
        lines.append("")
    return lines


def render_supported_formats_page() -> str:
    """Render the whole ``docs/guide/supported-formats.md`` page.

    Deterministic: the same registries always produce the same bytes, which is what makes the
    committed page drift-checkable.

    Returns:
        The complete Markdown document, newline-terminated.
    """
    rows = collect_format_rows()
    lines: List[str] = list(_header(rows))

    for paradigm, heading in _PARADIGM_SECTIONS:
        section_rows = [row for row in rows if row.paradigm is paradigm]
        if not section_rows:
            continue
        lines.append(f"## {heading}")
        lines.append("")
        lines.extend(_format_table(section_rows))
        lines.append("")

    lines.extend(_boundaries_section(rows))

    lines.extend(
        [
            "## Related",
            "",
            "- [How do I… import a specification?](import-a-spec.md)",
            "- [How do I… export a specification?](export-a-spec.md)",
            "- [Catalog format details](catalog-format-details.md) — what a catalog item "
            "records per format.",
            "- [Export fidelity](export-fidelity.md) — what survives a conversion between formats.",
            "",
        ]
    )

    return "\n".join(lines).rstrip("\n") + "\n"
