server {
    listen 443 ssl;
    server_name api.example.com;

    location /v2/orders {
        proxy_pass http://orders_backend;

    location /v2/products {
        proxy_pass http://catalogue_backend;
    }
}
