openapi: 3.0.1
info:
  title: broken
  version: "1.0"
paths:
  /ping:
    get:
      responses:
        "200":
         description: 200 response
      x-amazon-apigateway-integration:
          type: mock
        httpMethod: GET
