'use client';

import { useEffect, useState, type ComponentType, type ReactNode } from 'react';
import dynamic from 'next/dynamic';
import type { OnMount } from '@monaco-editor/react';
import { cn } from '@lib/utils';
import { guardedEditorOptions } from './exportViewerGuards';
import { CODE_EDITOR_FONT_SIZE } from '@/app/components/ui/code/editorTypography';
import {
  useHiveMonacoTheme,
  type MonacoThemeHost,
} from '@/app/components/ui/code/monacoHiveTheme';

/**
 * ReadOnlyCodeViewer — the shared read-only `@monaco-editor/react` viewer (MFX-43.1, #4361).
 *
 * The export flow shows generated bytes in several places — the Verify and Review steps and the
 * post-generate result — and every one wants the same thing: the emitted document, read-only, syntax
 * highlighted, matching the app's dark/light theme, loaded lazily. This is that one viewer, so those
 * surfaces (and the later bundle tree / diff / markers of MFX-43.2–43.5) share a single Monaco loader
 * rather than each re-deriving it.
 *
 * Monaco is code-split behind {@link https://nextjs.org/docs/app/api-reference/functions/dynamic |
 * next/dynamic} with `ssr: false` (Monaco touches `window`), matching the `ExportWizard.tsx`
 * precedent. If the editor chunk cannot load (offline, blocked CDN) the raw text still renders in a
 * `<pre>` fallback, so the artifact is never hidden behind a failed import.
 *
 * Accessibility (MFX-41.5): the container is a labelled region and Monaco's own textarea gets the
 * same name (`<document> — read-only <language> viewer`), so a screen-reader user is told which
 * document they landed in. Every viewer here is **read-only**, which is also what keeps it out of
 * keyboard-trap territory: Monaco only binds Tab to indentation on an editable model, so Tab moves
 * focus out of these editors normally.
 */

/** Offline fallback when the Monaco chunk cannot load — keeps the raw text visible and selectable. */
function OfflineCodeFallback({ value, fallbackTestId }: { value?: string; fallbackTestId?: string }) {
  return (
    <pre
      data-testid={fallbackTestId ?? 'read-only-code-content'}
      className="h-full overflow-auto whitespace-pre-wrap break-words p-3 font-mono text-xs leading-5 text-gray-800 dark:text-gray-200"
    >
      {value ?? ''}
    </pre>
  );
}

/** The props the viewer drives Monaco with — a subset of `EditorProps` plus the fallback's test id. */
interface ViewerEditorProps {
  height?: string | number;
  language?: string;
  theme?: string;
  value?: string;
  /** Forwarded by next/dynamic to {@link OfflineCodeFallback} if the editor chunk fails to load. */
  fallbackTestId?: string;
  options?: Record<string, unknown>;
  /** Defines the Hive theme before the editor is created — see {@link useHiveMonacoTheme}. */
  beforeMount?: (monaco: MonacoThemeHost) => void;
  onMount?: OnMount;
}

/**
 * The one shared Monaco loader for the export viewer surfaces. Declared at module scope so the chunk
 * is fetched once and reused; `.catch` degrades to the offline fallback, `loading` shows a spinner
 * placeholder while the chunk streams in. Typed as {@link ViewerEditorProps} so the `fallbackTestId`
 * next/dynamic passes through to the fallback is accepted (the real `EditorProps` ignore it).
 */
const MonacoEditor = dynamic(
  () =>
    import('@monaco-editor/react')
      .then((mod) => mod.default)
      .catch(() => OfflineCodeFallback),
  {
    ssr: false,
    loading: () => (
      <div className="flex h-full items-center justify-center text-sm text-gray-500 dark:text-gray-400">
        Loading viewer…
      </div>
    ),
  },
) as ComponentType<ViewerEditorProps>;

/** The fixed read-only editor options shared by every export viewer surface. */
const READ_ONLY_OPTIONS = {
  readOnly: true,
  domReadOnly: true,
  minimap: { enabled: false },
  fontSize: CODE_EDITOR_FONT_SIZE,
  fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace",
  lineNumbers: 'on' as const,
  scrollBeyondLastLine: false,
  padding: { top: 14, bottom: 14 },
  automaticLayout: true,
  // Markers (squiggles) are suppressed in read-only editors by default; the Verify problem
  // markers (MFX-43.3) need them rendered anyway.
  renderValidationDecorations: 'on' as const,
  renderLineHighlight: 'none' as const,
  overviewRulerLanes: 0,
  hideCursorInOverviewRuler: true,
  contextmenu: false,
  links: false,
  scrollbar: { verticalScrollbarSize: 8, horizontalScrollbarSize: 8 },
};

/**
 * Which palette the editor is painted in.
 *
 * `app` is Monaco's own `vs` / `vs-dark` pair, chosen by the `dark` class — what every export
 * surface has always used. `hive` is the app's live token palette
 * ({@link useHiveMonacoTheme}), which follows all nine themes rather than only the two: on
 * Whiteboard or Solarized, `vs-dark` is a black box on a page the reader asked to be pale.
 * New surfaces should ask for `hive`; the default stays `app` so no existing caller changes.
 */
export type ReadOnlyCodeViewerTheme = 'app' | 'hive';

export interface ReadOnlyCodeViewerProps {
  /** The document text to display. */
  value: string;
  /** The Monaco language id for syntax highlighting (e.g. `protobuf`, `graphql`, `json`). */
  language: string;
  /** Which palette to paint in. Defaults to `app` — Monaco's `vs` / `vs-dark`. */
  theme?: ReadOnlyCodeViewerTheme;
  /** Soft-wrap long lines. Defaults to `'off'` (emitted specs are read horizontally). */
  wordWrap?: 'on' | 'off';
  /**
   * Code folding. Defaults to on; the viewer surfaces expose it as a user toggle (MFX-43.5) rather
   * than deciding it by size, so the guard never silently overrides what the user asked for.
   */
  folding?: boolean;
  /** Optional control rendered pinned to the editor's top-right (e.g. a copy button). */
  overlay?: ReactNode;
  /**
   * Editor height. Defaults to `360` (a concrete pixel box) so Monaco always has a definite
   * viewport — `height: 100%` alone collapses to an empty white panel when the parent only has
   * `min-height` / flex grow without an explicit height (Export Studio Review).
   */
  height?: string | number;
  /** Extra classes for the editor container (borders, background, layout). */
  className?: string;
  /** `data-testid` for the editor container; it also carries `data-language` for assertions. */
  editorTestId?: string;
  /** `data-testid` for the offline `<pre>` fallback. */
  fallbackTestId?: string;
  /**
   * What this editor holds, e.g. `petstore.proto`. Names both the container region and Monaco's
   * own textarea ("… — read-only <language> viewer"), so a screen-reader user landing in the
   * editor is told which document they are in instead of hearing an unlabelled edit box
   * (MFX-41.5). Defaults to the language when the caller has no filename to give.
   */
  documentLabel?: string;
  /**
   * Monaco's mount callback `(editor, monaco) => void`, for callers that decorate the document —
   * the MFX-43.3 problem markers set squiggles/gutter bars and reveal lines through these handles.
   * Never called when the editor chunk fails and the `<pre>` fallback renders instead.
   */
  onMount?: OnMount;
}

/**
 * The shared read-only code viewer. With the default `theme="app"` it tracks the `dark` class
 * Next-Themes toggles on `<html>`, flipping between Monaco's `vs-dark` and `vs` live as the user
 * switches; with `theme="hive"` it paints from the app's own tokens instead, so it follows all
 * nine appearances rather than only light and dark (HIVE-6.6, #5317).
 *
 * @param props The document, its language, and presentation options.
 * @returns The read-only Monaco editor (or its offline fallback) in a themed container.
 */
export function ReadOnlyCodeViewer({
  value,
  language,
  theme = 'app',
  wordWrap = 'off',
  folding = true,
  overlay,
  height = 360,
  className,
  editorTestId = 'read-only-code-editor',
  fallbackTestId,
  documentLabel,
  onMount,
}: ReadOnlyCodeViewerProps) {
  const [isDark, setIsDark] = useState(false);
  // One name for the container region and for Monaco's textarea, so the two never disagree.
  const ariaLabel = `${documentLabel ?? language} — read-only ${language} viewer`;
  // Called unconditionally — a hook cannot be conditional, and defining the Hive theme costs
  // one `defineTheme` call whether or not this viewer is the one that asked for it.
  const hiveTheme = useHiveMonacoTheme();

  useEffect(() => {
    const sync = () => setIsDark(document.documentElement.classList.contains('dark'));
    sync();
    const observer = new MutationObserver(sync);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);

  // Pass a concrete pixel height straight into `@monaco-editor/react`. Nesting `height: 100%`
  // inside an absolutely-filled box collapses Monaco's internal flex host to ~one line (~10px)
  // even when the outer card looks tall — Copy still works because the model holds the text.
  // Built-in theme ids are `vs` / `vs-dark` (not `light`).
  const fillsParent = height === '100%';

  return (
    <div
      data-testid={editorTestId}
      data-language={language}
      role="group"
      aria-label={ariaLabel}
      className={cn('relative overflow-hidden', fillsParent && 'h-full min-h-[240px]', className)}
      style={fillsParent ? undefined : { height }}
    >
      {overlay ? <div className="absolute right-2 top-2 z-10">{overlay}</div> : null}
      <MonacoEditor
        height={fillsParent ? '100%' : height}
        language={language}
        theme={theme === 'hive' ? hiveTheme.theme : isDark ? 'vs-dark' : 'vs'}
        beforeMount={hiveTheme.beforeMount}
        value={value}
        fallbackTestId={fallbackTestId}
        // The size-guarded options (MFX-43.5) are computed from the text actually being rendered —
        // the guard upstream has already bounded that — so a big-but-admitted document drops the
        // whole-model extras rather than stalling the editor.
        options={{
          ...READ_ONLY_OPTIONS,
          ...guardedEditorOptions(value.length),
          folding,
          wordWrap,
          ariaLabel,
        }}
        onMount={onMount}
      />
    </div>
  );
}

export default ReadOnlyCodeViewer;
