apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-a-route
spec:
  replicas: 2
  selector:
    matchLabels:
      app: not-a-route
  template:
    metadata:
      labels:
        app: not-a-route
    spec:
      containers:
        - name: app
          image: nginx:1.27
