<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://example.com/billing"
                  targetNamespace="http://example.com/billing">
  <wsdl:message name="GetInvoiceRequest">
    <wsdl:part name="invoiceId" type="xs:string"/>
  </wsdl:message>
  <wsdl:portType name="BillingPortType">
    <wsdl:operation name="GetInvoice">
      <wsdl:input message="tns:GetInvoiceRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
