-- Oracle dialect: VARCHAR2/NUMBER/CLOB, sequences, identity, partitioning and
-- out-of-line constraints named the way an Oracle estate names them.

CREATE TABLE hr_employee (
    employee_id    NUMBER(10)     GENERATED BY DEFAULT AS IDENTITY,
    employee_no    VARCHAR2(12)   NOT NULL,
    first_name     VARCHAR2(40)   NOT NULL,
    last_name      VARCHAR2(60)   NOT NULL,
    email          VARCHAR2(255),
    hire_date      DATE           DEFAULT SYSDATE NOT NULL,
    department_id  NUMBER(6),
    salary         NUMBER(11,2),
    commission_pct NUMBER(3,2),
    notes          CLOB,
    photo          BLOB,
    updated_at     TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT hr_employee_pk PRIMARY KEY (employee_id),
    CONSTRAINT hr_employee_no_uq UNIQUE (employee_no),
    CONSTRAINT hr_employee_salary_ck CHECK (salary IS NULL OR salary > 0)
);

CREATE TABLE hr_department (
    department_id NUMBER(6)    NOT NULL,
    name          VARCHAR2(60) NOT NULL,
    cost_centre   VARCHAR2(10),
    CONSTRAINT hr_department_pk PRIMARY KEY (department_id)
);

ALTER TABLE hr_employee
    ADD CONSTRAINT hr_employee_dept_fk
    FOREIGN KEY (department_id) REFERENCES hr_department (department_id)
    ON DELETE SET NULL;

CREATE SEQUENCE hr_department_seq START WITH 100 INCREMENT BY 10 NOCACHE;

CREATE TABLE hr_payslip (
    payslip_id   NUMBER(12) NOT NULL,
    employee_id  NUMBER(10) NOT NULL,
    period_start DATE       NOT NULL,
    gross_amount NUMBER(11,2) NOT NULL,
    net_amount   NUMBER(11,2) NOT NULL,
    CONSTRAINT hr_payslip_pk PRIMARY KEY (payslip_id),
    CONSTRAINT hr_payslip_emp_fk FOREIGN KEY (employee_id)
        REFERENCES hr_employee (employee_id)
)
PARTITION BY RANGE (period_start) (
    PARTITION p2025 VALUES LESS THAN (DATE '2026-01-01'),
    PARTITION p2026 VALUES LESS THAN (DATE '2027-01-01'),
    PARTITION pmax  VALUES LESS THAN (MAXVALUE)
);

CREATE INDEX hr_employee_dept_ix ON hr_employee (department_id);

COMMENT ON TABLE hr_employee IS 'Employee master record.';
COMMENT ON COLUMN hr_employee.commission_pct IS 'Fraction, not percent: 0.15 means 15%.';
