#!/usr/bin/env python3
"""Generate the IXH-1.5 scale corpus at test time (#5091).

Nothing in the committed corpus approaches the size of the specs teams actually
hold — a multi-megabyte OpenAPI document, a registry snapshot with a thousand
record types, an EDI interchange carrying a thousand transaction sets. Import and
export timings over documents that size were therefore unmeasured, so a
regression in normalization or fidelity analysis would ship unnoticed.

Committing documents that large would bloat the repository permanently, so this
script is committed instead and the bytes are built on demand — the same
"generated by a committed script, keeping repo size flat" rule IXH-1.4 (#5090)
established for the adversarial tier.

:data:`SCALE_FIXTURES` is the checked-in spec: one entry per fixture naming the
paradigm it covers, the adapter it is imported through, and the emitter target the
export half drives. ``apiome-rest/tests/test_scale_corpus.py`` iterates it, so the
spec — not a directory listing — is the contract, and
``apiome-rest/tests/scale/scale_budgets.json`` holds one budget block per spec
entry.

Usage::

    # write every fixture into a directory (tests use a tmp_path)
    python3 scripts/generate_scale_corpus.py --out-dir /tmp/scale

    # list the spec without writing anything
    python3 scripts/generate_scale_corpus.py --list

Every builder is deterministic and takes its size knobs as default arguments, so
the same spec always produces byte-identical output and a regression is
reproducible from the fixture name alone. Every fixture is a **valid** document of
its format: the point is to measure honest work, not to trip a guard. They are all
sized below the 10 MiB ``maxDocumentBytes`` intake ceiling
(``apiome-rest/src/app/data/oas_resource_limits.json``) for the same reason — a
document the guards reject never reaches the stages being measured.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

__all__ = [
    "PARADIGMS",
    "SCALE_FIXTURES",
    "ScaleFixture",
    "build_fixture",
    "write_all",
]

#: Canonical paradigms the scale tier must cover, in the vocabulary the corpus
#: manifest's ``directories[*].paradigm`` uses. The IXH-1.5 acceptance criterion is
#: at least one scale fixture per entry here (REST, RPC, event, data-schema,
#: EDI/mainframe — the last being ``message`` plus the mainframe copybook, which the
#: manifest classifies as ``data_schema``).
PARADIGMS: tuple[str, ...] = ("rest", "rpc", "event", "data_schema", "message")


# ===========================================================================
# Builders
# ===========================================================================
#
# Each builder returns the fixture's raw bytes. Size knobs are default arguments
# so the shape of the document is readable and one number changes its scale.


def _openapi_large(paths: int = 550, schemas: int = 380, properties: int = 18) -> bytes:
    """A realistic OpenAPI 3.1 document of roughly 1.5 MiB.

    Wide rather than deep: every path carries one operation with query parameters
    and a ``$ref`` response, and every component schema carries a flat property
    block. That is the shape a large commercial API actually has, and it is what
    makes normalization, fingerprinting, and fidelity analysis expensive.

    Args:
        paths: Number of paths, each with one ``get`` operation.
        schemas: Number of component schemas the operations reference round-robin.
        properties: Properties per component schema.

    Returns:
        The document's UTF-8 JSON bytes.
    """
    components: Dict[str, Any] = {}
    for index in range(schemas):
        components[f"Entity{index:04d}"] = {
            "type": "object",
            "description": f"Entity {index:04d} of the scale corpus. " + "Descriptive prose. " * 3,
            "required": ["id"],
            "properties": {
                "id": {"type": "string", "format": "uuid"},
                **{
                    f"field_{ordinal:02d}": {
                        "type": "string",
                        "description": f"Field {ordinal:02d}. " + "Documented. " * 3,
                    }
                    for ordinal in range(properties)
                },
            },
        }

    document: Dict[str, Any] = {
        "openapi": "3.1.0",
        "info": {
            "title": "Scale corpus REST service",
            "version": "1.0.0",
            "description": "Generated by scripts/generate_scale_corpus.py (IXH-1.5, #5091).",
        },
        "servers": [{"url": "https://scale.example.com/v1"}],
        "paths": {},
        "components": {"schemas": components},
    }
    for index in range(paths):
        entity = f"Entity{index % schemas:04d}"
        document["paths"][f"/resources/{index:04d}"] = {
            "get": {
                "operationId": f"getResource{index:04d}",
                "summary": f"Read resource {index:04d}",
                "description": "Returns one resource. " + "Documented. " * 4,
                "tags": [f"group-{index % 24:02d}"],
                "parameters": [
                    {
                        "name": f"filter{ordinal}",
                        "in": "query",
                        "required": False,
                        "schema": {"type": "string"},
                    }
                    for ordinal in range(4)
                ],
                "responses": {
                    "200": {
                        "description": "The resource.",
                        "content": {
                            "application/json": {
                                "schema": {"$ref": f"#/components/schemas/{entity}"}
                            }
                        },
                    },
                    "404": {"description": "Not found."},
                },
            }
        }
    return json.dumps(document, indent=1).encode("utf-8")


def _openrpc_large(methods: int = 1500, schemas: int = 400, properties: int = 12) -> bytes:
    """An OpenRPC 1.2 document with 1500 methods (~1.5 MiB).

    The RPC analogue of the OpenAPI fixture: method count, not document depth, is
    what a large RPC surface costs.

    Args:
        methods: Number of methods on the service.
        schemas: Number of component schemas the methods reference round-robin.
        properties: Properties per component schema.

    Returns:
        The document's UTF-8 JSON bytes.
    """
    components = {
        f"Payload{index:04d}": {
            "type": "object",
            "properties": {
                f"f{ordinal:02d}": {"type": "string", "description": "Documented field."}
                for ordinal in range(properties)
            },
        }
        for index in range(schemas)
    }
    document: Dict[str, Any] = {
        "openrpc": "1.2.6",
        "info": {
            "title": "Scale corpus RPC service",
            "version": "1.0.0",
            "description": "Generated by scripts/generate_scale_corpus.py (IXH-1.5, #5091).",
        },
        "methods": [],
        "components": {"schemas": components},
    }
    for index in range(methods):
        payload = f"#/components/schemas/Payload{index % schemas:04d}"
        document["methods"].append(
            {
                "name": f"scale.method{index:05d}",
                "summary": f"Scale method {index:05d}",
                "description": "One generated RPC method. " + "Documented. " * 2,
                "params": [
                    {"name": f"arg{ordinal}", "required": ordinal == 0, "schema": {"$ref": payload}}
                    for ordinal in range(3)
                ],
                "result": {"name": "result", "schema": {"$ref": payload}},
            }
        )
    return json.dumps(document, indent=1).encode("utf-8")


def _cloudevents_large(attributes: int = 15000) -> bytes:
    """A CloudEvents 1.0 envelope whose ``data`` payload carries 15k attributes (~1.5 MiB).

    An event envelope is small by construction, so its scale axis is the payload:
    the normalizer infers one canonical type from ``data``, and this fixture makes
    that type enormous.

    Args:
        attributes: Number of top-level attributes in the event payload.

    Returns:
        The document's UTF-8 JSON bytes.
    """
    document = {
        "specversion": "1.0",
        "id": "scale-00000000-0000-0000-0000-000000000001",
        "type": "com.example.scale.snapshot.created",
        "source": "/scale/corpus/snapshots",
        "subject": "snapshot-0001",
        "time": "2024-01-01T00:00:00Z",
        "datacontenttype": "application/json",
        "data": {
            f"attribute_{index:05d}": {
                "value": index,
                "label": f"Attribute {index:05d}",
                "unit": "count",
            }
            for index in range(attributes)
        },
    }
    return json.dumps(document, indent=1).encode("utf-8")


def _avro_registry_large(records: int = 900, fields: int = 10) -> bytes:
    """An Avro record aggregating 900 nested record types (~1.5 MiB).

    Models the registry snapshot the problem statement names: one document whose
    every field is a distinct named record, so the normalizer produces a canonical
    model with nine hundred nested types.

    Args:
        records: Number of nested named record types.
        fields: Fields per nested record.

    Returns:
        The schema's UTF-8 JSON bytes.
    """
    members = [
        {
            "name": f"member_{index:04d}",
            "doc": f"Registry subject {index:04d}.",
            "type": {
                "type": "record",
                "name": f"Member{index:04d}",
                "doc": "One registered subject in the snapshot.",
                "fields": [
                    {
                        "name": f"field_{ordinal:02d}",
                        "type": ["null", "string"],
                        "default": None,
                        "doc": "Documented field.",
                    }
                    for ordinal in range(fields)
                ],
            },
        }
        for index in range(records)
    ]
    document = {
        "type": "record",
        "name": "RegistrySnapshot",
        "namespace": "com.example.scale",
        "doc": "Generated by scripts/generate_scale_corpus.py (IXH-1.5, #5091).",
        "fields": members,
    }
    return json.dumps(document, indent=1).encode("utf-8")


def _edi_x12_large(transaction_sets: int = 1500, lines_per_set: int = 10) -> bytes:
    """An ASC X12 004010 interchange carrying 1500 850 transaction sets (~0.6 MiB).

    Envelope counts are computed rather than hard-coded so the interchange stays
    internally consistent (``SE`` segment counts, ``GE``/``IEA`` totals) — pyx12
    reports count mismatches, and a fixture that trips them would measure error
    handling instead of parsing.

    Args:
        transaction_sets: Number of ``ST``/``SE`` transaction sets in the group.
        lines_per_set: ``PO1`` line items per transaction set.

    Returns:
        The interchange's UTF-8 bytes, one segment per line.
    """
    segments: List[str] = [
        "ISA*00*          *00*          *ZZ*SCALESENDER    *ZZ*SCALERECEIVER  "
        "*240101*1200*U*00401*000000001*0*P*>~",
        "GS*PO*SCALESENDER*SCALERECEIVER*20240101*1200*1*X*004010~",
    ]
    for index in range(transaction_sets):
        control = f"{index + 1:04d}"
        body = [f"BEG*00*SA*PO{index:06d}**20240101~"]
        for line in range(lines_per_set):
            body.append(f"PO1*{line + 1}*10*EA*9.99**BP*ITEM{line:05d}~")
        body.append(f"CTT*{lines_per_set}~")
        # ST + body + SE is the transaction set's own segment count.
        segments.append(f"ST*850*{control}~")
        segments.extend(body)
        segments.append(f"SE*{len(body) + 2}*{control}~")
    segments.append(f"GE*{transaction_sets}*1~")
    segments.append("IEA*1*000000001~")
    return ("\n".join(segments) + "\n").encode("utf-8")


def _cobol_copybook_large(fields: int = 7500) -> bytes:
    """A COBOL copybook declaring ~7500 elementary items (~0.4 MiB).

    The mainframe half of the EDI/mainframe paradigm: a single flat record layout
    of the size a long-lived VSAM copybook reaches.

    Args:
        fields: Number of elementary ``05`` items under the record.

    Returns:
        The copybook's UTF-8 bytes, in fixed-format columns.
    """
    lines = ["       01  SCALE-RECORD."]
    for index in range(fields):
        picture = "X(30)" if index % 3 else "9(9)"
        lines.append(f"           05  SCALE-FIELD-{index:05d}    PIC {picture}.")
    return ("\n".join(lines) + "\n").encode("utf-8")


# ===========================================================================
# Spec
# ===========================================================================


@dataclass(frozen=True)
class ScaleFixture:
    """One generated scale fixture and the pipeline coordinates it is measured on.

    Attributes:
        name: File name written into the output directory, and the fixture's key in
            the budget file and the benchmark report.
        paradigm: Canonical paradigm the fixture covers (see :data:`PARADIGMS`).
        adapter_key: ImportSource registry key the import half runs through.
        export_target: Emitter key the export half emits to. Chosen as the format's
            own emitter wherever one exists, so the measured export is the
            round-trip a user of that format would actually run.
        description: One line on what makes the fixture large.
        builder: Returns the fixture's bytes; deterministic and parameterless.
        approx_bytes: Rough on-disk size, for the suite's own budgeting.
        features: Corpus-style tags describing the fixture.
    """

    name: str
    paradigm: str
    adapter_key: str
    export_target: str
    description: str
    builder: Callable[[], bytes]
    approx_bytes: int = 0
    features: List[str] = field(default_factory=list)


#: The committed spec of generated scale fixtures. Tests iterate this list, and
#: ``apiome-rest/tests/scale/scale_budgets.json`` carries one budget block per name.
SCALE_FIXTURES: List[ScaleFixture] = [
    ScaleFixture(
        name="rest-openapi-large.json",
        paradigm="rest",
        adapter_key="openapi",
        export_target="openapi-3.1",
        description="OpenAPI 3.1 with 550 paths and 380 component schemas.",
        builder=_openapi_large,
        approx_bytes=1_545_000,
        features=["scale", "rest", "wide-paths", "component-schemas"],
    ),
    ScaleFixture(
        name="rpc-openrpc-large.json",
        paradigm="rpc",
        adapter_key="openrpc",
        export_target="openrpc",
        description="OpenRPC 1.2 with 1500 methods over 400 payload schemas.",
        builder=_openrpc_large,
        approx_bytes=1_456_000,
        features=["scale", "rpc", "method-count"],
    ),
    ScaleFixture(
        name="event-cloudevents-large.json",
        paradigm="event",
        adapter_key="cloudevents",
        export_target="cloudevents",
        description="CloudEvents 1.0 envelope with a 15000-attribute data payload.",
        builder=_cloudevents_large,
        approx_bytes=1_444_000,
        features=["scale", "event", "wide-payload"],
    ),
    ScaleFixture(
        name="data-schema-avro-registry.avsc",
        paradigm="data_schema",
        adapter_key="avro",
        export_target="avro",
        description="Avro snapshot aggregating 900 nested record types.",
        builder=_avro_registry_large,
        approx_bytes=1_567_000,
        features=["scale", "data-schema", "type-count", "registry-snapshot"],
    ),
    ScaleFixture(
        name="message-edi-x12-interchange.edi",
        paradigm="message",
        adapter_key="edix12",
        export_target="edix12",
        description="ASC X12 004010 interchange with 1500 850 transaction sets.",
        builder=_edi_x12_large,
        approx_bytes=576_000,
        features=["scale", "message", "edi", "transaction-sets"],
    ),
    ScaleFixture(
        name="mainframe-cobol-copybook-large.cpy",
        paradigm="data_schema",
        adapter_key="cobolcopybook",
        export_target="cobolcopybook",
        description="COBOL copybook declaring 7500 elementary items.",
        builder=_cobol_copybook_large,
        approx_bytes=350_000,
        features=["scale", "mainframe", "copybook", "field-count"],
    ),
]


def build_fixture(fixture: ScaleFixture, out_dir: Path) -> Path:
    """Materialize one fixture into ``out_dir``.

    Args:
        fixture: The spec entry to build.
        out_dir: Directory to write into; created if absent.

    Returns:
        The path written.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / fixture.name
    target.write_bytes(fixture.builder())
    return target


def write_all(out_dir: Path) -> List[Path]:
    """Materialize every fixture in :data:`SCALE_FIXTURES`.

    Args:
        out_dir: Directory to write into.

    Returns:
        The paths written, in spec order.
    """
    return [build_fixture(fixture, out_dir) for fixture in SCALE_FIXTURES]


def main(argv: Optional[List[str]] = None) -> int:
    """CLI entry point.

    Args:
        argv: Argument vector; defaults to ``sys.argv[1:]``.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out-dir", type=Path, help="Directory to write fixtures into.")
    parser.add_argument("--list", action="store_true", help="Print the spec and exit.")
    args = parser.parse_args(argv)

    if args.list or not args.out_dir:
        for fixture in SCALE_FIXTURES:
            print(
                f"{fixture.name:38s} {fixture.paradigm:12s} {fixture.adapter_key:14s} "
                f"-> {fixture.export_target:14s} {fixture.description}"
            )
        return 0

    for path in write_all(args.out_dir):
        print(f"wrote {path} ({os.stat(path).st_size} bytes)")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI
    sys.exit(main())
