"""Contract tests for the scale benchmark harness — IXH-1.5 (#5091).

The measurements themselves are opt-in and scheduled (:mod:`tests.test_scale_corpus`
runs for a minute and allocates hundreds of megabytes), but the machinery around
them must not be allowed to rot between scheduled runs. This module runs on every
PR and covers the three things that make the gate trustworthy:

* the **generator spec** covers every paradigm, and every fixture names an adapter
  and an emitter that exist and are runnable without an external toolchain — a
  fixture that silently could not run would remove a paradigm from the tier;
* the **committed baseline** has an entry for exactly the spec's fixtures and all
  ten stages, with a policy (margins, floors) that could actually fail a build;
* the **comparison rules** behave: over the margin fails, under it passes, and
  sub-floor noise is suppressed rather than reported.

Everything here is cheap: the only real work is building the fixture documents,
which the spec keeps to a few megabytes in total.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List

import pytest
from corpus_loader import load_manifest
from scale_benchmark import (
    ABSOLUTE_STAGE_PEAK_BYTES,
    ABSOLUTE_STAGE_SECONDS,
    BUDGET_VERSION,
    BUDGETS_PATH,
    DEFAULT_PEAK_FLOOR_BYTES,
    DEFAULT_WALL_FLOOR_MS,
    PEAK_MARGIN_ENV,
    REPORT_PATH_ENV,
    STAGE_ORDER,
    WALL_MARGIN_ENV,
    FixtureMeasurement,
    StageMeasurement,
    budgets_from_measurements,
    build_report,
    ceiling_breaches,
    compare,
    default_report_path,
    describe_breach,
    describe_regression,
    load_budgets,
    measure,
    peak_margin,
    render_budgets,
    report_path,
    wall_margin,
    write_report,
)
from scale_corpus_spec import (
    ENABLE_ENV,
    GENERATOR_PATH,
    load_generator,
    scale_fixtures,
    scale_paradigms,
    scale_suite_enabled,
)

from app.emitter import get_emitter, load_builtin_emitters
from app.import_source import (
    get_import_source,
    load_builtin_import_sources,
    resolve_import_source_key,
)

load_builtin_import_sources()
load_builtin_emitters()

#: The intake ceiling every scale fixture must stay under, so it is measured rather
#: than rejected (``app/data/oas_resource_limits.json`` ``maxDocumentBytes``).
_MAX_DOCUMENT_BYTES = 10 * 1024 * 1024


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _measurement(
    name: str = "fixture.json",
    *,
    wall_ms: float = 100.0,
    peak_bytes: int = 1_000_000,
    paradigm: str = "rest",
) -> FixtureMeasurement:
    """Build a synthetic measurement with the same value on every stage.

    Args:
        name: Fixture name.
        wall_ms: Wall-clock recorded for every stage.
        peak_bytes: Peak allocation recorded for every stage.
        paradigm: Paradigm label.

    Returns:
        A :class:`FixtureMeasurement` covering every stage in :data:`STAGE_ORDER`.
    """
    return FixtureMeasurement(
        name=name,
        paradigm=paradigm,
        adapter_key="openapi",
        export_target="openapi-3.1",
        source_bytes=1_000,
        stages={
            stage: StageMeasurement(stage=stage, wall_ms=wall_ms, peak_bytes=peak_bytes)
            for stage in STAGE_ORDER
        },
        process_peak_rss_bytes=2_000_000,
        detail={"types": 1},
    )


def _budgets(measurements: List[FixtureMeasurement], **policy: Any) -> Dict[str, Any]:
    """Build a budget document from measurements with an optional policy override."""
    document = budgets_from_measurements(measurements)
    document.update(policy)
    return document


# ---------------------------------------------------------------------------
# Generator spec
# ---------------------------------------------------------------------------


def test_generator_script_is_committed():
    """The fixtures are generated by a committed script, keeping repo size flat."""
    assert GENERATOR_PATH.exists(), f"missing committed generator: {GENERATOR_PATH}"


def test_every_paradigm_is_covered_by_the_spec():
    """Every required paradigm has at least one scale fixture.

    The first acceptance criterion, asserted against the spec so it holds even in
    runs that do not take the measurements.
    """
    covered = {fixture.paradigm for fixture in scale_fixtures()}
    missing = sorted(set(scale_paradigms()) - covered)
    assert not missing, f"scale spec covers no fixture for paradigm(s): {missing}"


def test_spec_paradigms_use_the_corpus_vocabulary():
    """Paradigm labels match the corpus manifest's, not a private spelling.

    ``data_schema`` versus ``data-schema`` is exactly the kind of drift that makes
    two coverage reports disagree about the same gap.
    """
    known = {directory.paradigm for directory in load_manifest().directories.values()}
    unknown = sorted(set(scale_paradigms()) - known)
    assert not unknown, f"paradigms not in the corpus manifest vocabulary: {unknown}"
    for fixture in scale_fixtures():
        assert fixture.paradigm in scale_paradigms(), (
            f"{fixture.name}: paradigm {fixture.paradigm!r} is outside the declared set"
        )


def test_every_fixture_names_a_runnable_adapter_and_emitter():
    """Each fixture's adapter and emitter exist, and need no external toolchain.

    A tool-gated adapter (``buf`` for protobuf, ``asyncapi-parser`` for AsyncAPI)
    would make its fixture skip wherever the toolchain is absent, quietly dropping a
    paradigm from the tier. The scale spec therefore only uses adapters that run
    everywhere.
    """
    problems: List[str] = []
    for fixture in scale_fixtures():
        adapter = get_import_source(resolve_import_source_key(fixture.adapter_key))
        if adapter is None:
            problems.append(f"{fixture.name}: unknown adapter {fixture.adapter_key!r}")
        elif getattr(adapter, "required_tools", ()):
            problems.append(
                f"{fixture.name}: adapter {fixture.adapter_key!r} requires "
                f"{list(adapter.required_tools)}, so the fixture would skip"
            )
        if get_emitter(fixture.export_target) is None:
            problems.append(f"{fixture.name}: unknown emit target {fixture.export_target!r}")
    assert not problems, "scale spec problems:\n  " + "\n  ".join(problems)


def test_fixture_names_are_unique():
    """Fixture names key the budget file, so a duplicate would shadow a budget."""
    names = [fixture.name for fixture in scale_fixtures()]
    assert len(names) == len(set(names)), f"duplicate scale fixture names: {names}"


def test_builders_are_deterministic_and_correctly_sized():
    """Building a fixture twice yields identical bytes of the declared size.

    Determinism is what makes a regression reproducible from a fixture name alone,
    and the size assertion keeps ``approx_bytes`` — which the suite budgets against
    — honest as the builders are tuned.
    """
    for fixture in scale_fixtures():
        first = fixture.builder()
        second = fixture.builder()
        assert first == second, f"{fixture.name}: builder is not deterministic"
        assert len(first) < _MAX_DOCUMENT_BYTES, (
            f"{fixture.name}: {len(first)} bytes is over the intake ceiling, so the "
            "document would be rejected instead of measured"
        )
        assert 0.5 <= len(first) / fixture.approx_bytes <= 2.0, (
            f"{fixture.name}: built {len(first)} bytes against a declared "
            f"approx_bytes of {fixture.approx_bytes}"
        )


def test_write_all_materializes_every_fixture(tmp_path):
    """The generator writes one file per spec entry, named as the spec declares."""
    written = load_generator().write_all(tmp_path)
    assert [path.name for path in written] == [f.name for f in scale_fixtures()]
    for path in written:
        assert path.stat().st_size > 0, f"{path.name}: generator wrote an empty fixture"


# ---------------------------------------------------------------------------
# Committed baseline
# ---------------------------------------------------------------------------


def test_committed_baseline_exists_and_is_canonically_formatted():
    """The baseline is committed in one place and stored in canonical form.

    Re-rendering the parsed document must reproduce the file byte for byte, so a
    refreshed baseline always lands as a numeric diff rather than a reformatting one.
    """
    assert BUDGETS_PATH.exists(), f"missing committed baseline: {BUDGETS_PATH}"
    text = BUDGETS_PATH.read_text(encoding="utf-8")
    assert render_budgets(json.loads(text)) == text, (
        f"{BUDGETS_PATH} is not canonically formatted; rewrite it with "
        "`pytest tests/test_scale_corpus.py --update-scale-budgets`"
    )


def test_committed_baseline_covers_exactly_the_spec():
    """Every spec fixture has a budget, and no budget outlives its fixture."""
    document = load_budgets()
    assert document["budget_version"] == BUDGET_VERSION
    budgeted = set(document["fixtures"])
    declared = {fixture.name for fixture in scale_fixtures()}
    assert budgeted == declared, (
        f"budgeted-but-undeclared: {sorted(budgeted - declared)}; "
        f"declared-but-unbudgeted: {sorted(declared - budgeted)}"
    )


def test_committed_baseline_budgets_every_stage_plausibly():
    """Every fixture budgets all ten stages with usable, in-ceiling numbers.

    A zero or missing budget can never fail, and a budget above the absolute ceiling
    would encode a broken pipeline as the accepted normal.
    """
    problems: List[str] = []
    for name, entry in load_budgets()["fixtures"].items():
        stages = entry.get("stages") or {}
        missing = sorted(set(STAGE_ORDER) - set(stages))
        if missing:
            problems.append(f"{name}: no budget for stage(s) {missing}")
        for stage, budget in stages.items():
            if budget["wall_ms"] <= 0:
                problems.append(f"{name}/{stage}: non-positive wall_ms budget")
            if budget["peak_bytes"] < 0:
                problems.append(f"{name}/{stage}: negative peak_bytes budget")
            if budget["wall_ms"] > ABSOLUTE_STAGE_SECONDS * 1000.0:
                problems.append(f"{name}/{stage}: wall budget is over the absolute ceiling")
            if budget["peak_bytes"] > ABSOLUTE_STAGE_PEAK_BYTES:
                problems.append(f"{name}/{stage}: peak budget is over the absolute ceiling")
    assert not problems, "committed baseline problems:\n  " + "\n  ".join(problems)


def test_committed_policy_can_actually_fail_a_build():
    """The margins and floors are set to values that still gate.

    A margin of 10x or a floor of a minute would leave the suite green through any
    regression; this pins the policy as a deliberate choice rather than a leftover.
    """
    document = load_budgets()
    assert 1.0 < document["regression_margin"] <= 3.0
    assert 1.0 < document["memory_margin"] <= 3.0
    assert 0 < document["wall_floor_ms"] <= 1000.0
    assert 0 < document["peak_floor_bytes"] <= 64 * 1024 * 1024


def test_baseline_records_the_machine_it_was_measured_on():
    """The baseline names its runtime, without which two runs are not comparable."""
    measured_on = load_budgets().get("measured_on") or {}
    assert measured_on.get("python"), "the baseline does not record its Python version"
    assert measured_on.get("platform"), "the baseline does not record its platform"


# ---------------------------------------------------------------------------
# Comparison rules
# ---------------------------------------------------------------------------


def test_a_run_matching_its_baseline_has_no_regressions():
    """The identity case: measurements equal to the budget pass."""
    measurements = [_measurement()]
    regressions, problems = compare(measurements, _budgets(measurements))
    assert regressions == []
    assert problems == []


def test_a_stage_over_the_margin_and_floor_is_a_regression():
    """A slow stage fails, and the failure names the fixture, stage, and ratio."""
    baseline = [_measurement(wall_ms=1000.0)]
    slower = [_measurement(wall_ms=2500.0)]
    regressions, problems = compare(slower, _budgets(baseline))
    assert problems == []
    assert {r.metric for r in regressions} == {"wall_ms"}
    assert len(regressions) == len(STAGE_ORDER)
    described = describe_regression(regressions[0])
    assert "fixture.json" in described and "2.50x" in described


def test_a_stage_under_the_margin_is_not_a_regression():
    """Drift the margin tolerates does not fail the build."""
    baseline = [_measurement(wall_ms=1000.0)]
    slightly_slower = [_measurement(wall_ms=1400.0)]
    regressions, _problems = compare(slightly_slower, _budgets(baseline))
    assert regressions == []


def test_sub_floor_noise_is_suppressed():
    """A fast stage that doubles is noise, not a regression.

    2 ms → 6 ms is a 3x ratio and utterly meaningless; without the absolute floor
    the suite would fail on scheduler jitter and be ignored within a week.
    """
    baseline = [_measurement(wall_ms=2.0, peak_bytes=1_000)]
    noisy = [_measurement(wall_ms=6.0, peak_bytes=5_000)]
    regressions, _problems = compare(noisy, _budgets(baseline))
    assert regressions == []


def test_memory_growth_is_gated_separately_from_time():
    """A stage that keeps its time but doubles its peak still fails."""
    baseline = [_measurement(peak_bytes=100 * 1024 * 1024)]
    hungry = [_measurement(peak_bytes=300 * 1024 * 1024)]
    regressions, _problems = compare(hungry, _budgets(baseline))
    assert {r.metric for r in regressions} == {"peak_bytes"}


def test_an_unbudgeted_fixture_is_a_problem_not_a_pass():
    """A fixture with no committed budget fails, with the refresh command in hand."""
    measurements = [_measurement(name="brand-new.json")]
    regressions, problems = compare(measurements, _budgets([_measurement(name="old.json")]))
    assert regressions == []
    assert any("brand-new.json" in problem for problem in problems)
    assert any("--update-scale-budgets" in problem for problem in problems)


def test_a_stale_budget_entry_is_a_problem():
    """A budget for a fixture the spec dropped is reported rather than ignored."""
    measurements = [_measurement(name="kept.json")]
    document = _budgets([_measurement(name="kept.json"), _measurement(name="dropped.json")])
    _regressions, problems = compare(measurements, document)
    assert any("dropped.json" in problem for problem in problems)


def test_a_stage_missing_from_a_budget_entry_is_a_problem():
    """A budget entry that lost a stage cannot silently stop gating it."""
    measurements = [_measurement()]
    document = _budgets(measurements)
    document["fixtures"]["fixture.json"]["stages"].pop("normalize")
    _regressions, problems = compare(measurements, document)
    assert any("'normalize'" in problem for problem in problems)


def test_margins_are_overridable_per_run(monkeypatch):
    """``SCALE_REGRESSION_MARGIN`` / ``SCALE_MEMORY_MARGIN`` win over the file."""
    document = _budgets([_measurement()], regression_margin=1.6, memory_margin=1.5)
    assert wall_margin(document) == 1.6
    monkeypatch.setenv(WALL_MARGIN_ENV, "2.5")
    monkeypatch.setenv(PEAK_MARGIN_ENV, "3.0")
    assert wall_margin(document) == 2.5
    assert peak_margin(document) == 3.0


def test_a_margin_below_one_is_rejected(monkeypatch):
    """A margin under 1.0 would fail every run; it is a typo, not a policy."""
    monkeypatch.setenv(WALL_MARGIN_ENV, "0.5")
    with pytest.raises(ValueError, match="multiplier"):
        wall_margin(_budgets([_measurement()]))


def test_absolute_ceilings_catch_a_breakage_without_any_baseline():
    """A hung or memory-hungry stage fails regardless of the committed numbers."""
    hung = [_measurement(wall_ms=ABSOLUTE_STAGE_SECONDS * 1000.0 + 1.0)]
    breaches = ceiling_breaches(hung)
    assert {breach.metric for breach in breaches} == {"wall_ms"}
    assert "absolute ceiling" in describe_breach(breaches[0])

    hungry = [_measurement(peak_bytes=ABSOLUTE_STAGE_PEAK_BYTES + 1)]
    assert {breach.metric for breach in ceiling_breaches(hungry)} == {"peak_bytes"}


def test_a_healthy_run_breaches_no_ceiling():
    """The ceilings do not fire on ordinary measurements."""
    assert ceiling_breaches([_measurement()]) == []


def test_default_policy_constants_are_consistent():
    """The fallback floors are positive, so a file without them still gates sanely."""
    assert DEFAULT_WALL_FLOOR_MS > 0
    assert DEFAULT_PEAK_FLOOR_BYTES > 0


# ---------------------------------------------------------------------------
# Report artifact
# ---------------------------------------------------------------------------


def test_report_carries_every_stage_with_its_budget_and_ratio():
    """The report pairs each measured stage with the budget it was held to."""
    measurements = [_measurement(wall_ms=1000.0, peak_bytes=1_000_000)]
    document = _budgets([_measurement(wall_ms=500.0, peak_bytes=500_000)])
    regressions, problems = compare(measurements, document)
    report = build_report(measurements, document, regressions, problems, [])

    [fixture] = report["fixtures"]
    assert tuple(fixture["stages"]) == STAGE_ORDER
    stage = fixture["stages"]["parse"]
    assert stage["budget"] == {"wall_ms": 500.0, "peak_bytes": 500_000}
    assert stage["wall_ratio"] == 2.0
    assert stage["peak_ratio"] == 2.0
    assert report["passed"] is False
    assert report["totals"]["fixtures"] == 1
    assert report["environment"]["python"]


def test_report_of_a_clean_run_passes():
    """A run inside its budgets reports ``passed`` with no findings."""
    measurements = [_measurement()]
    document = _budgets(measurements)
    regressions, problems = compare(measurements, document)
    report = build_report(measurements, document, regressions, problems, [])
    assert report["passed"] is True
    assert report["regressions"] == []
    assert report["problems"] == []
    assert report["breaches"] == []


def test_report_is_written_as_parseable_json(tmp_path):
    """The artifact round-trips through JSON, stages still in pipeline order."""
    measurements = [_measurement()]
    document = _budgets(measurements)
    report = build_report(measurements, document, [], [], [])
    written = write_report(report, tmp_path / "scale-report.json")
    reloaded = json.loads(written.read_text(encoding="utf-8"))
    assert reloaded == report
    assert tuple(reloaded["fixtures"][0]["stages"]) == STAGE_ORDER


def test_report_path_is_overridable(monkeypatch, tmp_path):
    """``SCALE_REPORT_PATH`` redirects the artifact; the default is under reports/."""
    monkeypatch.delenv(REPORT_PATH_ENV, raising=False)
    assert report_path() == default_report_path()
    assert default_report_path().parent.name == "reports"
    monkeypatch.setenv(REPORT_PATH_ENV, str(tmp_path / "elsewhere.json"))
    assert report_path() == tmp_path / "elsewhere.json"


# ---------------------------------------------------------------------------
# Measurement primitive and opt-in
# ---------------------------------------------------------------------------


def test_measure_records_time_and_allocation():
    """The primitive reports both metrics for the work it wraps."""
    # Distinct mutable buffers, not repeated literals: CPython folds ``"x" * 1024``
    # into one interned constant, so a list of them allocates almost nothing.
    payload, measurement = measure("parse", lambda: [bytearray(4096) for _ in range(512)])
    assert len(payload) == 512
    assert measurement.stage == "parse"
    assert measurement.wall_ms > 0
    assert measurement.peak_bytes > 1024 * 1024


def test_measure_stops_tracing_even_when_the_stage_raises():
    """A failing stage must not leave tracemalloc running for the next one."""
    import tracemalloc

    def _boom() -> None:
        raise RuntimeError("stage failed")

    with pytest.raises(RuntimeError, match="stage failed"):
        measure("parse", _boom)
    assert not tracemalloc.is_tracing()


def test_suite_is_opt_in(monkeypatch):
    """Without the flag or the variable, the scale suite does not run."""
    monkeypatch.delenv(ENABLE_ENV, raising=False)
    assert scale_suite_enabled(None) is False
    monkeypatch.setenv(ENABLE_ENV, "1")
    assert scale_suite_enabled(None) is True
