apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: team-gateway
  namespace: gateway-system
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
